# This is a basic workflow to help you get started with Actions
# there are 3 major parts of flow "name", "on" , "jobs"

# name anything you want
name: Boot Camp 2020

# Controls when the workflow will run
# they are the trigger when work flow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # for now we are having a trigger when we push code to main
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # what operating system you will run on your project
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # it will allow jobs to reach the repository code on which workflow process will execute
      - uses: actions/checkout@v3

      # installing node modules
      # name can be anything, name will show on action tab on github. it facilitates us to see on which step our flow has reached 
      # uses means that github itself provide some features to execute the desired task like installing node modules  
      - name: Installing node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 16
      # manually installing surge 
      - name: installing surge
        run: npm install --global surge
      # deployment process of our code on surge
      # ./ is for current directory where our code is
        # then url and then token which we setup in github secrets 
      - name: deploying using surge
        run: surge ./build class_2_starting_react.surge.sh --token ${{ secrets.CLASS_2_SECRET }}
